// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbTRvUwkd8J5-Yciv-_Kf9H_FwcsUs2HA',
    appId: '1:585793221474:web:7a3c59944e4c9b0acab23b',
    messagingSenderId: '585793221474',
    projectId: 'fir-dersleri-c5b9e',
    authDomain: 'fir-dersleri-c5b9e.firebaseapp.com',
    storageBucket: 'fir-dersleri-c5b9e.appspot.com',
    measurementId: 'G-H8JFKYWEZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSYGNMgIfh8R6faw6p11YU-jZ2f743CQ',
    appId: '1:585793221474:android:a5ec53c4935ac272cab23b',
    messagingSenderId: '585793221474',
    projectId: 'fir-dersleri-c5b9e',
    storageBucket: 'fir-dersleri-c5b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxfTLoY7OovkYeDQ7BxdItHQH23jYNt8',
    appId: '1:585793221474:ios:45367ccab116996bcab23b',
    messagingSenderId: '585793221474',
    projectId: 'fir-dersleri-c5b9e',
    storageBucket: 'fir-dersleri-c5b9e.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWxfTLoY7OovkYeDQ7BxdItHQH23jYNt8',
    appId: '1:585793221474:ios:4f08aa8dbd743f5ccab23b',
    messagingSenderId: '585793221474',
    projectId: 'fir-dersleri-c5b9e',
    storageBucket: 'fir-dersleri-c5b9e.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
